name: zifter-stack
version: '0.0.0.7'
synopsis: zifter-stack
description: zifter-stack
category: Zift
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: MIT
homepage: http://cs-syd.eu
dependencies:
- base >=4.9 && <=5
- Cabal >=1.24 && <2.1
- process
- filepath >=1.4 && <1.5
- directory
- zifter >=0.0 && <0.1
- path
- path-io
- safe >=0.3 && <0.4
library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Zifter.Stack
