flags: {}
extra-package-dbs: []
packages:
- zifter
- zifter-cabal
- zifter-git
- zifter-google-java-format
- zifter-hindent
- zifter-hlint
- zifter-stack

extra-deps:
- genvalidity-0.4.0.0
- genvalidity-hspec-0.5.0.0
- genvalidity-path-0.2.0.0
- genvalidity-property-0.1.0.0
- validity-0.4.0.0
- validity-path-0.2.0.0
resolver: lts-8.5
