flags: {}
extra-package-dbs: []
packages:
- zifter
- zifter-cabal
- zifter-git
- zifter-google-java-format
- zifter-hindent
- zifter-hlint
- zifter-stack
extra-deps:
- directory-1.3.0.2
- genvalidity-0.3.1.0
- genvalidity-hspec-0.3.0.0
- haskell-src-exts-1.19.1
- hlint-1.9.39
- optparse-applicative-0.13.0.0
- process-1.4.3.0
- validity-0.3.2.0
- validity-path-0.1.0.0
resolver: lts-7.14
