flags: {}
extra-package-dbs: []
packages:
- zifter
- zifter-cabal
- zifter-git
- zifter-google-java-format
- zifter-hindent
- zifter-hlint
- zifter-stack
extra-deps:
- genvalidity-0.3.1.0
- genvalidity-hspec-0.3.0.0
- genvalidity-path-0.1.0.2
- genvalidity-containers-0.2.0.1
- validity-0.3.2.0
- validity-path-0.1.0.0
- validity-containers-0.1.0.3
resolver: lts-8.5
