flags: {}
extra-package-dbs: []
packages:
- zifter
- zifter-cabal
- zifter-git
- zifter-google-java-format
- zifter-hindent
- zifter-hlint
- zifter-stack
resolver: lts-11.6
extra-deps:
- validity-0.6.0.0
- validity-path-0.3.0.1
- genvalidity-0.5.0.3
- genvalidity-hspec-0.6.0.3
- genvalidity-path-0.3.0.1
- genvalidity-property-0.2.0.2
