resolver: lts-7.14
packages:
- zifter
- zifter-cabal
- zifter-git
- zifter-google-java-format
- zifter-hindent
- zifter-hlint
- zifter-stack
extra-deps:
- genvalidity-hspec-0.3.0.0
- genvalidity-0.3.0.0
- validity-0.3.1.1
- hlint-1.9.39
- haskell-src-exts-1.19.1
flags: {}
extra-package-dbs: []
