name: zifter-google-java-format
version: '0.0.0.1'
synopsis: zifter-google-java-format
description: zifter-google-java-format
category: Zift
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: MIT
homepage: http://cs-syd.eu
dependencies:
- base >=4.9 && <=5
- zifter >=0.0.1.2 && <0.1
- path
- path-io
- process
- safe >=0.3 && <0.4
- filepath >=1.4 && <1.5
library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Zifter.GoogleJavaFormat
