name: zifter
version: '0.0.1.4'
synopsis: zifter
description: zifter
category: Zift
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: MIT
homepage: http://cs-syd.eu
dependencies:
- base >=4.9 && <=5
library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Zifter
  - Zifter.OptParse
  - Zifter.OptParse.Types
  - Zifter.Recurse
  - Zifter.Script
  - Zifter.Script.Types
  - Zifter.Setup
  - Zifter.Setup.Types
  - Zifter.Types
  - Zifter.Zift
  - Zifter.Zift.Types
  dependencies:
  - ansi-terminal >=0.6 && <0.8
  - async >=2.1 && <2.2
  - directory >=1.2 && <1.4
  - exceptions >=0.8 && <0.9
  - filepath >=1.4 && <1.5
  - optparse-applicative >=0.13 && <0.15
  - path >=0.5 && <0.7
  - path-io >1.2 && <1.4
  - process >=1.4 && <1.7
  - safe >=0.3 && <0.4
  - stm >=2.4 && <2.5
  - validity >=0.3 && <0.5
  - validity-path >=0.1 && <0.3
tests:
  zifter-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - zifter
    - QuickCheck >=2.9 && <2.11
    - colour >=2.3 && <2.4
    - genvalidity >=0.3 && <0.5
    - genvalidity-hspec >=0.3 && <0.6
    - genvalidity-path >=0.1 && <0.3
    - hspec
    - path
    - path-io
    - stm
    - ansi-terminal
    - directory
