name: zifter-git
version: '0.0.0.1'
synopsis: zifter-git
description: zifter-git
category: Zift
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: MIT
homepage: http://cs-syd.eu
dependencies:
- base >=4.9 && <=5
- zifter >=0.0 && <0.1
- process
- path
library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Zifter.Git
