resolver: lts-7.14
packages:
- /home/syd/cs-syd/code/open-source/introduction/introduction-test
- /home/syd/cs-syd/code/open-source/introduction/introduction
- /home/syd/cs-syd/code/open-source/validity/genvalidity-containers
- /home/syd/cs-syd/code/open-source/validity/genvalidity-hspec-aeson
- /home/syd/cs-syd/code/open-source/validity/genvalidity-hspec
- /home/syd/cs-syd/code/open-source/validity/genvalidity-text
- /home/syd/cs-syd/code/open-source/validity/genvalidity
- /home/syd/cs-syd/code/open-source/validity/validity-bytestring
- /home/syd/cs-syd/code/open-source/validity/validity-containers
- /home/syd/cs-syd/code/open-source/validity/validity-text
- /home/syd/cs-syd/code/open-source/validity/validity
- /home/syd/cs-syd/code/open-source/zifter
